# Generated by Django 4.2 on 2023-05-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='zadej nazev zanru', max_length=50, unique=True, verbose_name='Nazev zanru')),
            ],
            options={
                'verbose_name': 'zanr',
                'verbose_name_plural': 'zanry',
                'ordering': ['name'],
            },
        ),
    ]
