# Generated by Django 4.2 on 2023-05-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Race',
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['name'], 'verbose_name': 'race', 'verbose_name_plural': 'races'},
        ),
    ]
