# Generated by Django 4.2 on 2023-05-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_genre_race_alter_race_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(help_text='zadej nazev rasy', max_length=50, unique=True, verbose_name='race'),
        ),
    ]
