# Generated by Django 4.2 on 2023-05-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_body_part_alter_race_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body_part',
            options={'ordering': ['body_part'], 'verbose_name': 'body part', 'verbose_name_plural': 'body parts'},
        ),
        migrations.RemoveField(
            model_name='body_part',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='body_part',
            name='body_part',
            field=models.CharField(default='Full body', help_text='body part', max_length=50, unique=True, verbose_name='body part'),
        ),
    ]
