# Generated by Django 4.2.1 on 2023-05-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Difficulty', max_length=50, unique=True, verbose_name='Difficulty')),
            ],
            options={
                'verbose_name': 'difficulty',
                'verbose_name_plural': 'difficulty',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Race',
        ),
    ]
