# Generated by Django 4.2.1 on 2023-05-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_difficulty_delete_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exercise', max_length=50, unique=True, verbose_name='Exercise')),
                ('poster', models.ImageField(blank=True, help_text='grafický soubor', null=True, upload_to='posters', verbose_name='Plakát ')),
                ('body_part', models.ManyToManyField(help_text='body_part', to='myapp.body_part', verbose_name='body_part')),
                ('difficulty', models.ManyToManyField(help_text='Difficulty', to='myapp.difficulty', verbose_name='Difficulty')),
                ('equipment', models.ManyToManyField(help_text='equipment', to='myapp.equipment', verbose_name='equipment')),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
                'ordering': ['name'],
            },
        ),
    ]
