# Generated by Django 4.2 on 2023-06-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_exercise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body_part',
            options={'ordering': ['body_part'], 'verbose_name': 'body_part', 'verbose_name_plural': 'body_parts'},
        ),
    ]
