# Generated by Django 4.2 on 2023-06-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_body_part_exercise_body_parts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulties',
            field=models.ManyToManyField(to='myapp.difficulty', verbose_name='difficulties'),
        ),
    ]
