# Generated by Django 4.2 on 2023-06-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_exercise_difficulties'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='obsah',
            field=models.TextField(blank=True, help_text='obsah', verbose_name='obsah'),
        ),
    ]
